# Generated by Django 3.1.7 on 2021-08-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contect',
            name='address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='contect',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contect',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
